# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAS', '0002_auto_20160919_1528'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='careers',
            table='careers',
        ),
        migrations.AlterModelTable(
            name='clusters',
            table='clusters',
        ),
        migrations.AlterModelTable(
            name='coursecareer',
            table='course_career',
        ),
        migrations.AlterModelTable(
            name='courses',
            table='courses',
        ),
        migrations.AlterModelTable(
            name='groups',
            table='groups',
        ),
        migrations.AlterModelTable(
            name='subjects',
            table='subjects',
        ),
        migrations.AlterModelTable(
            name='universities',
            table='universities',
        ),
    ]
