# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAS', '0004_auto_20160920_1654'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='choices',
            table='choices',
        ),
    ]
