# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CAS', '0005_auto_20160920_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectCluster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAS.Clusters')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAS.Subjects')),
            ],
            options={
                'db_table': 'subject_cluster',
            },
        ),
    ]
