# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAS', '0007_auto_20160920_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='cutoff',
            field=models.FloatField(default=0),
        ),
    ]
