# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 09:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CAS', '0008_auto_20160920_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explanations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=1000)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'explanations',
            },
        ),
        migrations.CreateModel(
            name='KcseResults',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.CharField(max_length=10)),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAS.Subjects')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'KCSE_results',
            },
        ),
        migrations.CreateModel(
            name='Personalities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typology', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=1000)),
            ],
            options={
                'db_table': 'personalities',
            },
        ),
        migrations.CreateModel(
            name='PersonalityCareer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'personality_career',
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'question_answer',
            },
        ),
        migrations.CreateModel(
            name='RecommendedCourses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAS.Courses')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommended_courses',
            },
        ),
        migrations.AddField(
            model_name='choices',
            name='personality',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='careers',
            name='description',
            field=models.TextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='clusters',
            name='dscription',
            field=models.TextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='questions',
            name='text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='universities',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='choice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAS.Choices'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAS.Questions'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personalitycareer',
            name='career_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAS.Careers'),
        ),
        migrations.AddField(
            model_name='personalitycareer',
            name='pesonality_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAS.Personalities'),
        ),
    ]
