# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAS', '0009_auto_20160924_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='explanations',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='kcseresults',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='kcseresults',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='personalitycareer',
            old_name='career_id',
            new_name='career',
        ),
        migrations.RenameField(
            model_name='personalitycareer',
            old_name='pesonality_id',
            new_name='pesonality',
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='choice_id',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='recommendedcourses',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='recommendedcourses',
            old_name='user_id',
            new_name='user',
        ),
    ]
