# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAS', '0010_auto_20160924_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecareer',
            old_name='course_code',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='user_id',
            new_name='user',
        ),
    ]
