# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAS', '0013_grades_subjectgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
