# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 04:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAS', '0014_grades_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clusters',
            old_name='dscription',
            new_name='description',
        ),
    ]
