# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAS', '0015_auto_20161008_0430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalitycareer',
            old_name='pesonality',
            new_name='pesornality',
        ),
    ]
