# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAS', '0016_auto_20161016_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalitycareer',
            old_name='pesornality',
            new_name='personality',
        ),
    ]
