# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-12 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAS', '0017_auto_20161016_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='courses',
            name='overview',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='courses',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courses',
            name='tag',
            field=models.CharField(default='', max_length=200),
        ),
    ]
