# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-12 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAS', '0020_auto_20161112_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecareer',
            name='course',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
