# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAS', '0022_auto_20161112_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='category',
            field=models.CharField(default='', max_length=255),
        ),
    ]
