# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAS', '0024_auto_20161121_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendedcourses',
            name='course',
        ),
    ]
