# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 12:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CAS', '0028_remove_coursecareer_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedCourses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CAS.Courses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommended_courses',
            },
        ),
    ]
