# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAS', '0031_auto_20161121_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecareer',
            name='career',
        ),
        migrations.RemoveField(
            model_name='coursecareer',
            name='course',
        ),
        migrations.DeleteModel(
            name='CourseCareer',
        ),
    ]
