# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CAS', '0032_auto_20161121_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCareer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAS.Careers')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAS.Courses')),
            ],
            options={
                'db_table': 'course_career',
            },
        ),
    ]
