# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAS', '0033_coursecareer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='code',
            new_name='id',
        ),
    ]
