# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAS', '0037_auto_20161121_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='university',
        ),
        migrations.RemoveField(
            model_name='coursecareer',
            name='course',
        ),
        migrations.RemoveField(
            model_name='recommendedcourses',
            name='course',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
