# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CAS', '0038_auto_20161121_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='explanations',
            name='coursecareer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CAS.CourseCareer'),
        ),
    ]
