# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAS', '0041_explanations_coursecareer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explanations',
            name='coursecareer',
        ),
    ]
