# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CAS', '0042_remove_explanations_coursecareer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('duration', models.IntegerField(default=0)),
                ('cutoff', models.FloatField(default=0)),
                ('link', models.CharField(default='', max_length=200)),
                ('overview', models.TextField(default='', max_length=1000)),
                ('tag', models.CharField(default='', max_length=200)),
                ('position', models.IntegerField(default=0)),
                ('category', models.CharField(default='', max_length=255)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAS.Clusters')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAS.Universities')),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.AddField(
            model_name='coursecareer',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CAS.Courses'),
        ),
        migrations.AddField(
            model_name='recommendedcourses',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CAS.Courses'),
        ),
    ]
