# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAS', '0043_auto_20161121_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='id',
            new_name='code',
        ),
    ]
