# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 12:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CAS', '0045_auto_20161121_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCareer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAS.Careers')),
            ],
            options={
                'db_table': 'course_career',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('duration', models.IntegerField(default=0)),
                ('cutoff', models.FloatField(default=0)),
                ('link', models.CharField(default='', max_length=200)),
                ('overview', models.TextField(default='', max_length=1000)),
                ('tag', models.CharField(default='', max_length=200)),
                ('position', models.IntegerField(default=0)),
                ('category', models.CharField(default='', max_length=255)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAS.Clusters')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAS.Universities')),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='RecommendedCourses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CAS.Courses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommended_courses',
            },
        ),
        migrations.AddField(
            model_name='coursecareer',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CAS.Courses'),
        ),
    ]
