# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-23 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAS', '0046_auto_20161121_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careers',
            options={'verbose_name_plural': 'Careers'},
        ),
        migrations.AlterModelOptions(
            name='choices',
            options={'verbose_name_plural': 'Choices'},
        ),
        migrations.AlterModelOptions(
            name='clusters',
            options={'verbose_name_plural': 'Clusters'},
        ),
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='explanations',
            options={'verbose_name_plural': 'Explanations'},
        ),
        migrations.AlterModelOptions(
            name='grades',
            options={'verbose_name_plural': 'Grades'},
        ),
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='personalities',
            options={'verbose_name_plural': 'Personalities'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterModelOptions(
            name='universities',
            options={'verbose_name_plural': 'Universities'},
        ),
    ]
