# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAS', '0049_auto_20161124_0427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choices',
            options={'ordering': ['id'], 'verbose_name_plural': 'Choices'},
        ),
    ]
