# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAS', '0050_auto_20161126_0628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choices',
            old_name='choice',
            new_name='text',
        ),
    ]
