# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 06:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CAS', '0051_auto_20161126_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAS.Courses')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAS.Universities')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Favorites',
                'verbose_name_plural': 'Favorites',
            },
        ),
    ]
