# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAS', '0052_favorites'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='favorites',
            table='favorites',
        ),
    ]
